import com.techno.chess.ChessBoard;
import com.techno.chess.exception.InvalidInputException;

import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        String out;
        try (Scanner sc = new Scanner(System.in)) {
            System.out.print("Input : ");
            String input = sc.nextLine();
            out = new ChessBoard(input).getAvailableMoves();
        } catch (InvalidInputException e) {
            out = e.getMessage();
        }

        System.out.println("Output : " + out);
    }
}
