import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Scanner sc= new Scanner(System.in);
        System.out.print("Input : ");
        String input = sc.nextLine();
        System.out.println("Thanks for entering " + input + " implementation is in progress");
    }
}
